name: Update TryHackMe Badge

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch TryHackMe Badge
        run: |
          curl -o tryhackme-badge.png "https://tryhackme-badges.s3.amazonaws.com/thanuj23.png"

      - name: Commit and Push Badge
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tryhackme-badge.png
          git commit -m "Update TryHackMe Badge"
          git push
